highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
title: "Yvan Richard"
url: "https://yvyx04.github.io"
baseurl: "/yvanrichard.github.io"
plugins:
  # - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - github-pages
  # - jekyll-katex
